### ISSUE TITLE
SC: add a geolift example

### ISSUE THREAD

**Issue by drbenvincent** [pymc-labs/CausalPy#134]
A very popular use case of synthetic control is evaluating the causal impact of a treatment over different units. More specifically, this could be used to assess the impact of sales caused by an advertising campaign. But the **outcome variable** could be anything such as sales, user sign-ups, customer satisfaction etc. The **intervention** could be an advertising campaign, the renovation of a store, the change of a company policy. The **treatment units** could be stores, geographical regions. But the commonality is the question "What was the causal impact of an intervention?"

## Implementation
We can do everything we need with the `SyntheticControl` class. All we need is in an example dataset and to create a notebook.

At a later stage, we might consider creating a specific class which subclasses `SyntheticControl` (or alternatively build with mixins). This could be useful if we want to create a lot of custom functionality around this use case.

## Related work
* [CausalImpact](https://google.github.io/CausalImpact/CausalImpact.html)
* [GeoLift](https://facebookincubator.github.io/GeoLift/)

## Todo list

- [x] Get a dataset.
- [x] Create an example dataset + add it to dataset tests
- [x] Add to integration tests
- [x] Add example to the docs
